//url=https://opensource-demo.orangehrmlive.com/
url=https://www.demo.guru99.com/v4
UserId=mngr471474
UserPass=egYtesy
browser=chrome
URLNoCommerce=https://admin-demo.nopcommerce.com/login?ReturnUrl=%2Fadmin%2F